# Generated by Django 5.1.4 on 2024-12-06 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autoridades', '0001_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=10)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('autoridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoridades.autoridad')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
        ),
    ]
